### ISSUE TITLE
Not working on iOS 8.3

### ISSUE THREAD

**Issue by frakman1** [julioverne/DropbearAlert#1]
I am using iOS 8.3 on an iPhone 5S.

I can ssh into my phone via external PC and from iPhone terminal but I don't get any notifications. I've enabled everything in the DropBearAlert app and I've enabled all notifications for Dropbear under Settings-> Notifications. Is this supposed to work with the standard installation of openSSH from Cydia  or something else?

**Comment by nik312123** [comment]
I think it has to do with the part that says "**for iOS 10**."
